import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('global_co2.csv')
X = dataset.iloc[221:, 0:1].values
y = dataset.iloc[221:, 1:2].values
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, y)
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X)
poly_reg.fit(X_poly, y)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly, y)
plt.scatter(X, y)
plt.plot(X, lin_reg.predict(X))
plt.title('annual temp of 2 industries (Linear Regression)')
plt.xlabel('years')
plt.ylabel('avg temps')
plt.show()
plt.scatter(X, y)
plt.plot(X, lin_reg_2.predict(poly_reg.fit_transform(X)))
plt.title('annual temp of 2 industries (Polynomial Regression)')
plt.xlabel('years')
plt.ylabel('avg temps')
plt.show()
X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, y, color = 'red')
plt.plot(X_grid, lin_reg_2.predict(poly_reg.fit_transform(X_grid)))
plt.title('annual temp of 2 industries (Polynomial Regression)')
plt.xlabel('years')
plt.ylabel('avg temps')
plt.show()
lin_reg.predict([[2011]])
lin_reg.predict([[2012]])
lin_reg.predict([[2013]])
print('prediction of co2 in 2011 using (linear reg)')
print (lin_reg.predict([[2011]]))
print('prediction of co2 in 2012 using (linear reg)')
print (lin_reg.predict([[2012]]))
print('prediction of co2 in 2013 using (linear reg)')
print (lin_reg.predict([[2013]]))
# Predicting a new result with Polynomial Regression
lin_reg_2.predict(poly_reg.fit_transform([[2011]]))
lin_reg_2.predict(poly_reg.fit_transform([[2012]]))
lin_reg_2.predict(poly_reg.fit_transform([[2013]]))
print ('prediction of co2 in 2011 using (poly reg)')
print (lin_reg_2.predict(poly_reg.fit_transform([[2011]])))
print ('prediction of co2 in 2012 using (poly reg)')
print (lin_reg_2.predict(poly_reg.fit_transform([[2012]])))
print ('prediction of co2 in 2013 using (poly reg)')
print (lin_reg_2.predict(poly_reg.fit_transform([[2013]])))