import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('annual_temp.csv')
X = dataset.iloc[:, 1:2].values
y = dataset.iloc[:, 2].values
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, y)
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X)
poly_reg.fit(X_poly, y)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly, y)
plt.scatter(X, y, color = 'red')
plt.plot(X, lin_reg.predict(X), color = 'blue')
plt.title('annual temp of 2 industries (Linear Regression)')
plt.xlabel('years')
plt.ylabel('avg temps')
plt.show()
plt.scatter(X, y, color = 'red')
plt.plot(X, lin_reg_2.predict(poly_reg.fit_transform(X)), color = 'blue')
plt.title('annual temp of 2 industries (Polynomial Regression)')
plt.xlabel('years')
plt.ylabel('avg temps')
plt.show()
X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, y, color = 'red')
plt.plot(X_grid, lin_reg_2.predict(poly_reg.fit_transform(X_grid)), color = 'blue')
plt.title('annual temp of 2 industries (Polynomial Regression)')
plt.xlabel('years')
plt.ylabel('avg temps')
plt.show()
lin_reg.predict([[2016]])
lin_reg.predict([[2017]])
print('avg temp of 2 industries in 2016 using (linear reg)')
print (lin_reg.predict([[2016]]))
print('avg temp of 2 industries in 2017 using (linear reg)')
print (lin_reg.predict([[2017]]))
lin_reg_2.predict(poly_reg.fit_transform([[2016]]))
lin_reg_2.predict(poly_reg.fit_transform([[2017]]))
print ('avg temp of 2 industries in 2016 using (poly reg)')
print (lin_reg_2.predict(poly_reg.fit_transform([[2016]])))
print ('avg temp of 2 industries in 2017 using (poly reg)')
print (lin_reg_2.predict(poly_reg.fit_transform([[2017]])))